### ISSUE TITLE
Is there any Inference to test on an Image or a video?

### ISSUE THREAD

**Issue by BakingBrains** [skelemoa/synse-zsl#12]

**Comment by pranaygupta36** [comment]
Hi, the trained models are provided for zsl/gzsl for skeletal action recognition. Although we dont have a script which directly runs on a test image or video because as far as I know, kinect based joint estimation is not possible without kinect, the following however could be a strategy to obtain predictions.

1. Obtain skeleton joint coordinates from an action video, the provided models are trained on NTU-120,60 datasets which use kinect based 3d joint prediction. Make sure the joints you obtain are in the same order as that. Refer the NTU-60/120 dataset for the joint ordering. 
2. Once you have the joints, get the embeddings via the pre-trained Shift-GCN model, pass those embeddings through the pre-trained SynSE and obtain the prediction. However, the prediction from the zsl model would be from the unseen classes of the corresponding pre-trained model split and the prediction from the gzsl model would be one from the 120/60 classes of the NTU dataset, depending on the pretrained model you chose.

**Comment by BakingBrains** [comment]
@pranaygupta36 Thank you
