### ISSUE TITLE
[Questions] Only calling Dataloader once per epoch? Training classifier from scratch at each cycle?

### ISSUE THREAD

**Issue by WurmD** [skelemoa/synse-zsl#6]
at  synse/synse_training.py
```
def train_one_cycle(cycle_num, cycle_length):
...
    for epoch in range(s_epoch, e_epoch):
...
        (inputs, target) = next(iter(train_loader))


if __name__ == "__main__":
...
            train_one_cycle(num_cycle, cycle_length)
...
            zsl_acc, val_out_embs, cls = train_classifier()

```
the dataloader is only called once per epoch, so only 64 samples are used for training each epoch, and a classifier is trained from scratch after each cycle.

- Did you test training with all training samples per epoch and concluded only training with a few samples per epoch gave better results?

- Did you test training the classifier from where it left off last cycle and concluded training from scratch each time gave better results?

**Comment by pranaygupta36** [comment]
I believe we could have used a better naming convention for the variables. The variable 'epoch' here refers to each iteration. Basically a random batch of 64 samples is loaded each time `next(iter(train_loader))` is called. Therefore the VAEs sees all the samples while training.

To answer the second question, no we didn't resume training the classifier from where it was left off in the last cycle, because after each cycle the generated embeddings pertaining to the unseen classes are different, and the classifier is trained such that it optimally classifies the embeddings generated at the end of the current cycle.
